# -*- coding: utf-8 -*-
# Author: GAO--HUI
# Date: 2022-10-02 17:29:58
# LastEditors: GAO--HUI
# LastEditTime: 2022-10-14 22:27:35
# FilePath: \新版本\main.py


import time, os, base64
import login
from update import check, update

# ico = base64.b64decode(
#     "AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAOICAADiAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZzAHJXA4FMR4QSDAeEEgwGsyDaIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqLwk8zLerv///////////gU8vxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGorCxhqKwAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGovCTzMt6u///////////+BTy/FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGktCCJ1Px2/r416xZ13XctpMAmWgEAABAAAAAAAAAAAAAAAAAAAAAAAAAAAai8JPMy3q7///////////4FPL8UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAczwbvvn49+D+/v7//v7+/9rLwsFqLwlxAAAAAAAAAAAAAAAAAAAAAAAAAABqLwk8zLerv///////////gU8vxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGsoDROoh2/H/v7+//7+/v/+/v7//v7++W40D7kAAAAAAAAAAAAAAAAAAAAAAAAAAGovCTzMt6u///////////+BTy/FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbSQAB5VrUM3+/v7//v7+//7+/v/9/PzobDALqgAAAAAAAAAAAAAAAAAAAAAAAAAAai8JPMy3q7///////////4FPL8UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAajAJi9C/s7/+/v70+/v55Zt0WctrMQk5AAAAAAAAAAAAAAAAAAAAAAAAAABqLwk8zLerv///////////gU8vxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaS8KaGovCbRrLgmlaS4JOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGovCTzMt6u///////////+BTy/FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAai8JPMy3q7///////////4FPL8UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqLwk8zLerv///////////gU8vxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr2AgEK1jJT6pZB9KpmEhXKZiInClYCF6ol8gjo5NF7KpgGHf2cCq3f38++uBTy/FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGYzAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWVBzJi0sX+793K+bJfzDhzoQx39KHNN3bjzfa3ZA429+SON7jlTvZnmg89XtEIM4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABrLwhiajAItgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALaSJAePUBjg24432fWlQv/1pUL/9aVC//WlQv/1pUL/9aVC//WlQv/woUDgfUAR+qxoJDEAAAAAAAAAAAAAAAAAAAAAay8IYn9BEsVsLwvCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKqAKwaPTxjf24832vWlQv/1pUL/9aVC//WlQv/1pUL/9aVC//WlQv/woUDgjU0Y86xoJDEAAAAAAAAAAGkvCGF+PxHF86NB+20zCsQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKqAKwaPTxjf24832vWlQv/1pUL/9aVC//WlQv/1pUL/9aVC//WlQv/woUDgjU0Y86xoJDFpLwhhfj8RxfOjQfv1pUL/bzMMxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL+AIAiKShfk1Ik05fWlQv/1pUL/9aVC//WlQv/1pUL/9aVC//WlQv/woUDggUMR+H5BEMzzo0H79aVC//WlQv9xNQ3JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbDEKGnk7DsuaWR35z4Qy5vWlQv/1pUL/9aVC//WlQv/1pUL/9aVC/9GGM+h6PhH/8KJA/vWlQv/1pUL/9aVC/3M3DswAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG8sCxd1OQ7I7qA/1vWlQvyiYSD4zoMx6fWlQv/1pUL/9aVC//WlQv/RhjPoej0Q/++hQP/1pUL/9aVC//WlQv/1pUL/djgOzgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsMQoadjkOye+gP9X1pUL/9aVC//WlQvyjXyH5wHgs5qhkIsSoYyPEwHgs5ns+Ef/xoUD/9aVC//WlQv/1pUL/9aVC//WlQv95Ow/KZjMACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbDEKGng6DsrwoD/Z9aVC//WlQv/1pUL/9aVC//OjQeSMXTz0/fz64v38+uKLWzv15JU56PWlQv/1pUL/9aVC//WlQv/1pUL/9aVC/35AEcZtMQwVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGYzAAp4Og7K8KA/2fWlQv/1pUL/9aVC//WlQv/1pUL/3pI5wuHVz8P//////////+HVzcK3cCjE9aVC//WlQv/1pUL/9aVC//WlQv/voD/0cTUM0mMrDhIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZjMKGaplI8X1pUL/9aVC//WlQv/1pUL/9aVC//WlQv/unj/TrIt10///////////rIp11NWINtX1pUL/9aVC//WlQv/1pUL/76A/9HU5DsppLQpJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABtNwAOoF0eyfWlQv/1pUL/9aVC//WlQv/1pUL/9aVC/8+FM9mISRTwkWNE0ZFjRNGISRTwkFAX2vWlQv/1pUL/9aVC/++gP/R1OQ7KaS0KSQAAAAAAAAAAdC4AC2ovCH1qMAmmaTAKZoAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAIBAAASYVh3N9aVC//WlQv/1pUL/9aVC//WlQv/QhTPZnloe7PWlQvv1pUL89aVC/PWlQvucWR3qjEwX2/WlQv/voT/1dzoOymouCk0AAAAAAAAAAAAAAAFxOBS36eLcx/38/OrQvrK/azAKhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJJRGc31pUL/9aVC//WlQv/1pUL/0IUz2Z1YHuz1pUL69aVC//WlQv/1pUL/9aVC//WlQvygXB7ri0sX2nU5DsppLQpJAAAAAAAAAAAAAAAAbC4IIbOVg8P+/v7//v7+//7+/v+KWj3KZzEGKmowCaZqLwmOYicADQAAAAAAAAAAikoXyvWlQv/1pUL/9aVC/9qON8Z1OQ739KRC8fWlQv/1pUL/9aVC//WlQv/1pUL/9aVC//WlQvudWh7oai8JjgAAAAAAAAAAAAAAAAAAAABqKwsYpIFqyP7+/v/+/v7//v7++4BNLMl6RSPF/Pr54uni3MdqLwmMAAAAAAAAAACERBPH9aVC//WlQv/bjzfEazALqmgvCkyUUhrL9KRC9PWlQv/1pUL/9aVC//WlQv/1pUL/9aVC//WlQvypZCPEai8KZwAAAAAAAAAAAAAAAAAAAABsMAqVyLKkv+3n48qqiHLFajAIYIVWN83+/v78+fj332kvCaIAAAAAAAAAAHw+EcX1pUL/2o83w2swC6pmMwAFAAAAAGouC0iUUhrL9KRC9PWlQv/1pUL/9aVC//WlQv/1pUL/9aVC//WlQvypZCPEai8KZwAAAAAAAAAAAAAAAAAAAABrMApKai8JcWwxCjQAAAAAai8JV4VUNcx5QyHCaS4HJwAAAAAAAAAAdDkOwtqPN8NrMAuqZjMABQAAAAAAAAAAAAAAAGouC0iUUhvK9KRC9PWlQv/1pUL/9aVC//WlQv/1pUL/9aVC//WlQvypZCPEai8KZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABrMQnBajELqIBAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAGktCkmVUxvK9aVC9PWlQvv0pELv86RB5vGiQeHuoD/W7J4+0ueZPMt+QRHhajAIWwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGktCjOAQAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGouC0hqLgnAai4Ku2owCatqLwmkay8ImWovCYxpMAqFaS8Jd2suCW5rLQg+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//g////4P//z+D//wPg//8D4P/+A+D//gPg//8D4P//B+D////g////4P//8AD+//AA/P/wAHj/+AAw//wAAP/+AAD//gAA//wAAH/4AAB/8AAAf+AAAH/gAAD/4AABg+AAAwPwAAcAMAAPADAAB4AwQAPEMOAB//HwAP/z+AD8="
# )

# if not os.path.exists(os.path.join(os.getcwd(), "ic.ico")):
#     with open("ic.ico", "wb") as f:
#         f.write(ico)


if not login.check():
    login.write_info()

if check():
    login.tesk()
    update()
else:
    print("检测到没有驱动哦！下面将下载驱动，请手动联网")
    update(checked=True)

    print()
    print()
    print()
    print("下次连接校园网欢迎再试哦~")
    time.sleep(3)
